### ISSUE TITLE
Добавление функциянала взаимодействия с контенттом joomla 

### ISSUE THREAD

**Issue by rinka88** [sergeytolkachyov/WT-Bootstrap-image-slider#1]
А не хотите добавить нового разделе чтобы управлять / показывать joomla контент на слайдер.
Было бы отлично если можно будет выводить материалы категории на слайдере

**Comment by sergeytolkachyov** [comment]
@rinka88 здравствуйте. Для этого создается свой макет стандартного модуля новостей (в tmpl модуля) и выбирается затем в настройках модуля.

**Comment by rinka88** [comment]
Просто имел ввиду из коробки модуля🙂

**Comment by sergeytolkachyov** [comment]
> Просто имел ввиду из коробки модуля🙂

Такие вещи обычно нужны всем по-разному: кому-то картинку на фон с бэкдропом и ссылкой на весь баннер, кому-то нужно 3 новости в ряд карточкой, кому-то одна большая и 3 маленьких снизу/справа/слева/сверху и т.д. Не говоря о параметрах выборки материалов.
Поэтому модуль превратится в монстра в плане настроек. Для слайдера контента лучше использовать модуль новостей, в частности [JUNewsUltra](https://github.com/Joomla-Ukraine/JUNewsUltra) опять-таки со своим макетом.
