### ISSUE TITLE
Php 8.x

### ISSUE THREAD

**Issue by rinka88** [sergeytolkachyov/WT-Bootstrap-image-slider#2]
При переходе сайта на php 8.0, выдает ошибку

**Comment by sergeytolkachyov** [comment]
@rinka88 привет. Какая именно ошибка? В админке сайта или снаружи?

**Comment by rinka88** [comment]
![IMG_20230206_133138_520](https://user-images.githubusercontent.com/40716604/216922798-5064f039-1bce-4749-a623-a2a78aac6c20.jpg)
В админке все нормально, но сайт фронт падает, если включить php 8.0

**Comment by sergeytolkachyov** [comment]
Ошибка была только при указанном индивидуальном времени слайда. Исправлено. v.2.1.1
